### ISSUE TITLE
Omit authorization header from logs

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#139] opened 2018-11-02 09:22 UTC
#### Description
**Is**:

```
2018-09-11 10:33:12 WARNING <16> [api]: API: Unknown API Error with status code: 422 ({"body":{"error":"Balloon\\Filesystem\\Exception\\Conflict","message":"could not add node file.txt into a deleted parent collection","code":21},"reqOptions":{"uri":"https://server/api/v1//node/move","method":"POST","headers":{"User-Agent":"Balloon-Desktop-App||xxx|darwin|17.7.0","X-Client":"Balloon-Desktop-App||xxx","Authorization":"Bearer BEARER_TOKEN_HERE"},"body":{"id":"5b967b5ff9fb2802166479ff","destp":"/folder"},"json":true,"timeout":30000}})
2018-09-11 10:33:12 ERROR <16> [unknown]: LOCALQUEUEHANDLER: Unknown API Error with status code: 422 E_BLN_API_REQUEST_UNDEFINED_ERROR
```

**Should**:
Remove Authorization from reqOptions.headers.

#### balloon desktop version
v0.2.3

**Comment by pixtron** [comment] 2018-11-06 15:03
This is a duplicate of: gyselroth/balloon-node-sync/issues/13 and is fixed with v0.2.4

**Closed by pixtron** 2018-11-06 15:03 UTC
Labels: change
