### ISSUE TITLE
Feedback occasionally sends corrupt zip

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#107] opened 2018-06-25 06:37 UTC
#### Description
**Is**:
Feedback sends corrupt zip. (Can be extracted anyway using jar)

**Should**:
Valid zip file.

#### balloon desktop version
0.2.0

#### Your client operating system
Windows 10

**Comment by pixtron** [comment] 2018-06-25 07:02
Looks like a duplicate of #105

**Comment by pixtron** [comment] 2018-07-01 12:11
There is a regression introduced to #105. If fsInfo fails, and snapshot has not yet been appended to archive, the archiver will fail with `Error: append: queue closed`

**Closed** 2018-07-01 12:33 UTC
Labels: bug, windows
